import React, { useEffect, useRef } from 'react';
import { Animated, Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, radius, spacing, type } from '../theme';

export function VoiceAnswerControl({ audioState, disabled, onStart, onStop, compact = false }) {
  const active = audioState === 'listening' || audioState === 'processing';
  const label = audioState === 'listening' ? 'Listening...' : audioState === 'processing' ? 'Processing...' : 'Speak Answer';
  return <Pressable accessibilityRole="button" accessibilityLabel={active ? 'Stop voice answer' : 'Speak answer'} accessibilityState={{ busy: audioState === 'processing', disabled: Boolean(disabled) }} style={({ pressed }) => [styles.voiceButton, compact && styles.compact, disabled && !active && styles.disabled, pressed && styles.pressed]} onPress={active ? onStop : onStart} disabled={disabled && !active}>
    <Microphone active={audioState === 'listening'} /><Text style={styles.voiceText}>{label}</Text>
  </Pressable>;
}
function Microphone({ active }) { const pulse = useRef(new Animated.Value(0)).current; useEffect(() => { if (!active) { pulse.setValue(0); return; } const loop = Animated.loop(Animated.sequence([Animated.timing(pulse, { toValue: 1, duration: 850, useNativeDriver: true }), Animated.timing(pulse, { toValue: 0, duration: 850, useNativeDriver: true })])); loop.start(); return () => loop.stop(); }, [active, pulse]); return <View style={styles.micWrap}>{active ? <Animated.View style={[styles.pulse, { opacity: pulse.interpolate({ inputRange: [0, 1], outputRange: [0.3, 0] }), transform: [{ scale: pulse.interpolate({ inputRange: [0, 1], outputRange: [1, 1.65] }) }] }]} /> : null}<View style={styles.micCapsule} /><View style={styles.micStem} /><View style={styles.micBase} /></View>; }
export function ListenControl({ disabled, isSpeaking, onPress }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={isSpeaking ? 'Pause voice' : 'Listen'} style={({ pressed }) => [styles.listenButton, disabled && styles.disabled, pressed && styles.pressed]} onPress={onPress} disabled={disabled}><View style={styles.speakerBox}><View style={styles.speakerCone} />{isSpeaking ? <><View style={styles.waveOne} /><View style={styles.waveTwo} /></> : null}</View><Text style={styles.listenText}>{isSpeaking ? 'Speaking...' : 'Listen'}</Text></Pressable>;
}
export function VoiceStatus({ audioState, error, transcript }) {
  if (!error && !transcript && !['listening', 'processing'].includes(audioState)) return null;
  return <View accessibilityLiveRegion="polite" style={[styles.statusPanel, error && styles.errorPanel]}><View style={[styles.statusMark, error && styles.errorMark]}><Text style={styles.statusMarkText}>{error ? '!' : transcript ? 'OK' : '...'}</Text></View><View style={styles.statusCopy}>
    {transcript ? <><Text style={styles.statusTitle}>Voice recognized</Text><Text style={styles.transcript}>"{transcript}"</Text><Text style={styles.hint}>Edit if needed before continuing.</Text></> : null}
    {error ? <><Text style={styles.statusTitle}>Voice unavailable</Text><Text style={styles.error}>Please try again or type your answer.</Text></> : null}
    {!error && !transcript && audioState === 'listening' ? <><Text style={styles.statusTitle}>Listening...</Text><Text style={styles.hint}>Speak when you are ready.</Text></> : null}
    {!error && !transcript && audioState === 'processing' ? <><Text style={styles.statusTitle}>Processing...</Text><Text style={styles.hint}>Preparing your answer.</Text></> : null}
  </View></View>;
}
const styles = StyleSheet.create({
  voiceButton: { alignItems: 'center', backgroundColor: colors.mint, borderColor: colors.primary, borderRadius: radius.button, borderWidth: 1.5, flexDirection: 'row', justifyContent: 'center', minHeight: 58, paddingHorizontal: spacing.lg }, compact: { flex: 1 }, micWrap: { alignItems: 'center', height: 28, justifyContent: 'center', marginRight: spacing.sm, width: 28 }, pulse: { backgroundColor: colors.primary, borderRadius: 14, height: 28, position: 'absolute', width: 28 }, micCapsule: { borderColor: colors.primary, borderRadius: 6, borderWidth: 2, height: 15, width: 10 }, micStem: { backgroundColor: colors.primary, height: 5, width: 2 }, micBase: { backgroundColor: colors.primary, borderRadius: 2, height: 2, width: 12 }, voiceText: { ...type.button, color: colors.primary },
  listenButton: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: colors.surface, borderColor: colors.primary, borderRadius: radius.pill, borderWidth: 1, flexDirection: 'row', justifyContent: 'center', marginTop: spacing.md, minHeight: 46, paddingHorizontal: spacing.lg }, speakerBox: { height: 20, marginRight: spacing.sm, width: 24 }, speakerCone: { backgroundColor: colors.primary, borderRadius: 2, height: 12, left: 2, position: 'absolute', top: 4, width: 9 }, waveOne: { borderColor: colors.primary, borderLeftWidth: 0, borderRadius: 8, borderRightWidth: 1.5, height: 12, position: 'absolute', right: 5, top: 4, width: 7 }, waveTwo: { borderColor: colors.primary, borderLeftWidth: 0, borderRadius: 10, borderRightWidth: 1.5, height: 18, position: 'absolute', right: 0, top: 1, width: 10 }, listenText: { ...type.body, color: colors.primary, fontWeight: '900' }, disabled: { opacity: 0.48 }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] },
  statusPanel: { backgroundColor: colors.mint, borderColor: colors.border, borderRadius: radius.small, borderWidth: 1, flexDirection: 'row', gap: spacing.md, marginTop: spacing.md, padding: spacing.md }, errorPanel: { backgroundColor: colors.errorBg }, statusMark: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 14, height: 28, justifyContent: 'center', width: 28 }, errorMark: { backgroundColor: colors.error }, statusMarkText: { color: colors.white, fontSize: 10, fontWeight: '900' }, statusCopy: { flex: 1 }, statusTitle: { ...type.meta, color: colors.text, fontWeight: '900' }, transcript: { ...type.body, color: colors.text, marginTop: 2 }, hint: { ...type.meta, color: colors.secondary, marginTop: 2 }, error: { ...type.meta, color: colors.error, marginTop: 2 },
});
