import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { getWellnessTrends } from '../api/emotionalSupportApi';
import { Card, Greeting, InlineState, MetaChip, OrganicIcon, ScreenHeader, WellnessBackdrop } from '../components/WellnessUI';
import { useEmotionalSupportContext } from '../context/EmotionalSupportContext';
import { activityStyles, colors, radius, screenInsets, shadows, spacing, type } from '../theme';
import { getPersonalizedGreeting } from '../utils/personalization';
const pretty = (value = '') => String(value).replace(/_(easy|medium)$/i, '').replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
export default function ElderHomeScreen({ navigation }) {
  const { elderId, user } = useEmotionalSupportContext(); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const greeting = useMemo(() => getPersonalizedGreeting(user), [user]);
  const load = useCallback(async () => { try { setLoading(true); setError(false); if (!elderId) throw new Error(); setData(await getWellnessTrends(elderId, '7d')); } catch { setError(true); } finally { setLoading(false); } }, [elderId]);
  useEffect(() => { load(); }, [load]);
  const recent = data?.activities?.recent_activity_log?.[0]; const key = String(recent?.activity_code || '').replace(/_(easy|medium)$/i, ''); const look = activityStyles[key] || { accent: colors.primary, soft: colors.mint, symbol: '✓' };
  return <SafeAreaView style={s.safe}><WellnessBackdrop /><ScrollView contentContainerStyle={s.container}>
    <Greeting text={greeting} subtitle="Ready for a short check-in?" /><ScreenHeader title="Emotional & Cognitive Support" subtitle="Check in, stay engaged, and review your wellness journey." />
    <View style={s.hero}><View style={s.heroGlow} /><OrganicIcon color={colors.white} soft="#FFFFFF22" label="CARE" /><Text style={s.heroEyebrow}>DAILY WELLNESS</Text><Text style={s.heroTitle}>Daily Adaptive Check-In</Text><Text style={s.heroText}>A gentle moment to notice how you are feeling today.</Text><View style={s.featureRow}><MetaChip label="5 Questions" tint="#FFFFFF1F" color={colors.white} /><MetaChip label="Voice Enabled" tint="#FFFFFF1F" color={colors.white} /><MetaChip label="~3 Minutes" tint="#FFFFFF1F" color={colors.white} /></View><Pressable accessibilityRole="button" style={({ pressed }) => [s.primary, pressed && s.pressed]} onPress={() => navigation.navigate('AdaptiveSupportChatScreen')}><Text style={s.primaryText}>Start Check-In</Text><Text style={s.arrow}>›</Text></Pressable></View>
    <Text style={s.sectionTitle}>Explore &amp; Engage</Text><View style={s.exploreRow}><Pressable accessibilityRole="button" onPress={() => navigation.navigate('CognitiveActivityLibraryScreen')} style={({ pressed }) => [s.explorePressable, pressed && s.pressed]}><Card style={[s.exploreCard, s.lavenderCard]}><OrganicIcon color="#705E9B" soft="#EEE8FA" label="PLAY" /><Text style={s.linkTitle}>Cognitive Activities</Text><Text style={s.linkText}>8 activities to choose from</Text><Text style={s.exploreArrow}>Explore ›</Text></Card></Pressable><Pressable accessibilityRole="button" onPress={() => navigation.navigate('EmotionalTrendScreen')} style={({ pressed }) => [s.explorePressable, pressed && s.pressed]}><Card style={[s.exploreCard, s.skyCard]}><OrganicIcon color={colors.info} soft={colors.sky} label="UP" /><Text style={s.linkTitle}>Wellness Trends</Text><Text style={s.linkText}>Your recent wellness journey</Text><Text style={s.exploreArrow}>View ›</Text></Card></Pressable></View>
    <Text style={s.sectionTitle}>Recent activity</Text><InlineState loading={loading} error={error} onRetry={load} empty={!loading && !error && !recent} emptyTitle="No activities yet" emptyText="Complete a short check-in to begin building your wellness history." />
    {recent && !loading ? <Pressable accessibilityRole="button" onPress={() => navigation.navigate('EmotionalTrendScreen')} style={({ pressed }) => pressed && s.pressed}><Card style={s.recentCard}><View style={s.recentRow}><OrganicIcon color={look.accent} soft={look.soft} label={look.symbol} /><View style={s.linkCopy}><Text style={s.linkTitle}>{pretty(recent.activity_code)}</Text><Text numberOfLines={1} style={s.linkText}>{recent.accuracy == null ? 'Completed' : `Activity Accuracy ${Math.round(recent.accuracy * 100)}%`}</Text></View><Text style={s.chevron}>›</Text></View></Card></Pressable> : null}
    <Text style={s.disclaimer}>This feature supports wellbeing and engagement and is not a medical diagnosis.</Text>
  </ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, container: { paddingHorizontal: spacing.xl, paddingTop: screenInsets.top, paddingBottom: screenInsets.bottom + spacing.xl }, hero: { ...shadows.level3, backgroundColor: colors.primary, borderRadius: radius.hero, marginBottom: spacing.xxl, overflow: 'hidden', padding: spacing.xxl }, heroGlow: { backgroundColor: '#FFFFFF12', borderRadius: 100, height: 180, position: 'absolute', right: -45, top: -65, width: 180 }, heroEyebrow: { ...type.meta, color: '#CFEAE4', letterSpacing: 1, marginTop: spacing.lg }, heroTitle: { ...type.section, color: colors.white, fontSize: 26, marginTop: spacing.xs }, heroText: { ...type.body, color: '#EAF6F2', marginTop: spacing.sm }, featureRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.lg }, primary: { alignItems: 'center', backgroundColor: colors.white, borderRadius: radius.button, flexDirection: 'row', justifyContent: 'center', marginTop: spacing.xl, minHeight: 58 }, primaryText: { ...type.button, color: colors.primary }, arrow: { color: colors.primary, fontSize: 28, marginLeft: spacing.sm }, sectionTitle: { ...type.card, color: colors.text, marginBottom: spacing.md, marginTop: spacing.xs }, exploreRow: { flexDirection: 'row', gap: spacing.md, marginBottom: spacing.xxl }, explorePressable: { flex: 1 }, exploreCard: { minHeight: 190, padding: spacing.lg }, lavenderCard: { backgroundColor: '#F7F3FD' }, skyCard: { backgroundColor: '#F8FCFE' }, exploreArrow: { color: colors.primary, fontSize: 15, fontWeight: '900', marginTop: 'auto', paddingTop: spacing.md }, recentCard: { backgroundColor: '#FCFAFF' }, linkCopy: { flex: 1, marginLeft: spacing.md, minWidth: 0 }, linkTitle: { ...type.card, color: colors.text, marginTop: spacing.md }, linkText: { ...type.meta, color: colors.secondary, marginTop: spacing.xs }, chevron: { color: colors.primary, fontSize: 31 }, recentRow: { alignItems: 'center', flexDirection: 'row' }, disclaimer: { ...type.meta, color: colors.secondary, marginTop: spacing.xl, textAlign: 'center' }, pressed: { opacity: 0.84, transform: [{ scale: 0.988 }] } });
