import React, { useCallback, useState } from 'react';
import { KeyboardAvoidingView, Platform, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { startAdaptiveActivity, submitAdaptiveActivity } from '../api/emotionalSupportApi';
import { VoiceAnswerControl, VoiceStatus, ListenControl } from '../components/VoiceControls';
import { Button, Card, InlineState, OrganicIcon, ScreenHeader, WellnessBackdrop } from '../components/WellnessUI';
import useEnglishVoice from '../voice/useEnglishVoice';
import { colors, radius, screenInsets, spacing, type } from '../theme';

export default function ReminiscenceActivityScreen({ navigation, route }) {
  const activity = route?.params?.recommended_activity || {}; const context = route?.params?.activity_context || {};
  const [memory, setMemory] = useState(''); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [voiceTranscript, setVoiceTranscript] = useState(''); const { width } = useWindowDimensions();
  const handleTranscript = useCallback((transcript) => { setMemory(transcript); setVoiceTranscript(transcript); }, []); const voice = useEnglishVoice({ onTranscript: handleTranscript });
  const prompt = activity.instructions || 'Think of a place that has brought you comfort. What do you remember most about it?';
  const canComplete = Boolean(activity.activity_code && context.session_id && context.user_id && memory.trim()) && !loading && !result && !voice.isListening;
  async function complete() { if (!canComplete) return; try { voice.stopAll(); setLoading(true); setError(''); const attempt = await startAdaptiveActivity({ ...context, activity_code: activity.activity_code }); setResult(await submitAdaptiveActivity(attempt.attempt_id, { user_id: context.user_id, response: { narrative: memory.trim() } })); } catch { setError('Unable to save this activity.'); } finally { setLoading(false); } }
  return <SafeAreaView style={s.safe}><WellnessBackdrop variant="warm" /><KeyboardAvoidingView style={s.flex} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled">
    <ScreenHeader navigation={navigation} eyebrow="GENTLE REMINISCENCE" title={activity.title || 'A Pleasant Memory'} subtitle="A gentle moment to remember something meaningful." />
    {!result ? <>
      <Card style={s.promptCard}><View style={s.promptTop}><OrganicIcon color="#9A654C" soft="#FFFFFF88" label="MEM" /><Text style={s.promptLabel}>TODAY'S MEMORY PROMPT</Text></View><View style={s.quoteMark}><Text style={s.quoteText}>“</Text></View><Text style={s.promptText}>{prompt}</Text><ListenControl isSpeaking={voice.isSpeaking} onPress={() => voice.isSpeaking ? voice.stopSpeaking() : voice.speak(prompt)} /></Card>
      <Card style={s.answerCard}><Text style={s.answerTitle}>Share your memory</Text><Text style={s.helper}>Share as much or as little as feels comfortable.</Text><TextInput accessibilityLabel="Your memory" style={s.input} value={memory} onChangeText={setMemory} editable={!loading} multiline textAlignVertical="top" placeholder="Type your memory..." placeholderTextColor={colors.secondary} /><VoiceStatus audioState={voice.audioState} error={voice.voiceError} transcript={voiceTranscript} /></Card>
      <View style={[s.actions, width < 370 && s.actionsNarrow]}><VoiceAnswerControl compact audioState={voice.audioState} disabled={loading} onStart={voice.startListening} onStop={() => voice.stopListening()} /><Button style={s.actionButton} label="Complete Activity" loading={loading} disabled={!canComplete} onPress={complete} /></View>
      {error ? <InlineState error /> : null}
    </> : <Card style={s.complete}><View style={s.check}><Text style={s.checkText}>OK</Text></View><Text style={s.completeTitle}>Activity Complete</Text><Text style={s.completeCopy}>{result.feedback || 'Thank you for sharing your memory.'}</Text><Button label="View Trends" onPress={() => navigation.navigate('EmotionalTrendScreen')} style={s.fullButton} /><Button variant="secondary" label="Done" onPress={() => navigation.popToTop()} style={s.secondary} /></Card>}
  </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { backgroundColor: '#FFF9F3', flex: 1 }, flex: { flex: 1 }, container: { paddingHorizontal: spacing.xl, paddingTop: screenInsets.top, paddingBottom: screenInsets.bottom + spacing.xl }, promptCard: { backgroundColor: '#FFF0E6', overflow: 'hidden' }, promptTop: { alignItems: 'center', flexDirection: 'row' }, promptLabel: { ...type.meta, color: '#8A5D47', flex: 1, letterSpacing: 0.8, marginLeft: spacing.md }, quoteMark: { alignItems: 'center', backgroundColor: '#FFFFFF88', borderRadius: 22, height: 44, justifyContent: 'center', position: 'absolute', right: spacing.xl, top: spacing.xl, width: 44 }, quoteText: { color: '#B67B61', fontSize: 35, lineHeight: 44 }, promptText: { ...type.question, color: colors.text, marginTop: spacing.xl }, answerCard: { marginTop: spacing.lg }, answerTitle: { ...type.card, color: colors.text }, helper: { ...type.meta, color: colors.secondary, marginTop: spacing.xs }, input: { ...type.body, backgroundColor: colors.background, borderColor: colors.border, borderRadius: 18, borderWidth: 1, color: colors.text, marginTop: spacing.md, minHeight: 118, padding: spacing.lg }, actions: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.lg }, actionsNarrow: { flexDirection: 'column' }, actionButton: { flex: 1 }, complete: { alignItems: 'center', marginTop: spacing.md }, check: { alignItems: 'center', backgroundColor: colors.mint, borderRadius: 38, height: 76, justifyContent: 'center', width: 76 }, checkText: { color: colors.primary, fontSize: 15, fontWeight: '900' }, completeTitle: { ...type.section, color: colors.text, marginTop: spacing.lg }, completeCopy: { ...type.body, color: colors.secondary, marginTop: spacing.sm, textAlign: 'center' }, fullButton: { marginTop: spacing.xl, width: '100%' }, secondary: { marginTop: spacing.md, width: '100%' } });
